# Generated by Django 4.0.2 on 2022-10-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='mail',
            field=models.CharField(max_length=50),
        ),
    ]
